// Code generated by ent, DO NOT EDIT.

package entbalance

import (
	"tracker/core/balance"
	"tracker/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Balance {
	return predicate.Balance(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Balance {
	return predicate.Balance(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Balance {
	return predicate.Balance(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Balance {
	return predicate.Balance(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Balance {
	return predicate.Balance(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Balance {
	return predicate.Balance(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Balance {
	return predicate.Balance(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Balance {
	return predicate.Balance(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Balance {
	return predicate.Balance(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Balance {
	return predicate.Balance(sql.FieldEQ(FieldTitle, v))
}

// UsdToCurrency applies equality check predicate on the "usd_to_currency" field. It's identical to UsdToCurrencyEQ.
func UsdToCurrency(v float64) predicate.Balance {
	return predicate.Balance(sql.FieldEQ(FieldUsdToCurrency, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Balance {
	return predicate.Balance(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Balance {
	return predicate.Balance(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Balance {
	return predicate.Balance(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Balance {
	return predicate.Balance(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Balance {
	return predicate.Balance(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Balance {
	return predicate.Balance(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Balance {
	return predicate.Balance(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Balance {
	return predicate.Balance(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Balance {
	return predicate.Balance(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Balance {
	return predicate.Balance(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Balance {
	return predicate.Balance(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Balance {
	return predicate.Balance(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Balance {
	return predicate.Balance(sql.FieldContainsFold(FieldTitle, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v balance.Currency) predicate.Balance {
	vc := v
	return predicate.Balance(sql.FieldEQ(FieldCurrency, vc))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v balance.Currency) predicate.Balance {
	vc := v
	return predicate.Balance(sql.FieldNEQ(FieldCurrency, vc))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...balance.Currency) predicate.Balance {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Balance(sql.FieldIn(FieldCurrency, v...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...balance.Currency) predicate.Balance {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Balance(sql.FieldNotIn(FieldCurrency, v...))
}

// UsdToCurrencyEQ applies the EQ predicate on the "usd_to_currency" field.
func UsdToCurrencyEQ(v float64) predicate.Balance {
	return predicate.Balance(sql.FieldEQ(FieldUsdToCurrency, v))
}

// UsdToCurrencyNEQ applies the NEQ predicate on the "usd_to_currency" field.
func UsdToCurrencyNEQ(v float64) predicate.Balance {
	return predicate.Balance(sql.FieldNEQ(FieldUsdToCurrency, v))
}

// UsdToCurrencyIn applies the In predicate on the "usd_to_currency" field.
func UsdToCurrencyIn(vs ...float64) predicate.Balance {
	return predicate.Balance(sql.FieldIn(FieldUsdToCurrency, vs...))
}

// UsdToCurrencyNotIn applies the NotIn predicate on the "usd_to_currency" field.
func UsdToCurrencyNotIn(vs ...float64) predicate.Balance {
	return predicate.Balance(sql.FieldNotIn(FieldUsdToCurrency, vs...))
}

// UsdToCurrencyGT applies the GT predicate on the "usd_to_currency" field.
func UsdToCurrencyGT(v float64) predicate.Balance {
	return predicate.Balance(sql.FieldGT(FieldUsdToCurrency, v))
}

// UsdToCurrencyGTE applies the GTE predicate on the "usd_to_currency" field.
func UsdToCurrencyGTE(v float64) predicate.Balance {
	return predicate.Balance(sql.FieldGTE(FieldUsdToCurrency, v))
}

// UsdToCurrencyLT applies the LT predicate on the "usd_to_currency" field.
func UsdToCurrencyLT(v float64) predicate.Balance {
	return predicate.Balance(sql.FieldLT(FieldUsdToCurrency, v))
}

// UsdToCurrencyLTE applies the LTE predicate on the "usd_to_currency" field.
func UsdToCurrencyLTE(v float64) predicate.Balance {
	return predicate.Balance(sql.FieldLTE(FieldUsdToCurrency, v))
}

// HasTransactions applies the HasEdge predicate on the "transactions" edge.
func HasTransactions() predicate.Balance {
	return predicate.Balance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TransactionsTable, TransactionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTransactionsWith applies the HasEdge predicate on the "transactions" edge with a given conditions (other predicates).
func HasTransactionsWith(preds ...predicate.Transaction) predicate.Balance {
	return predicate.Balance(func(s *sql.Selector) {
		step := newTransactionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Balance) predicate.Balance {
	return predicate.Balance(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Balance) predicate.Balance {
	return predicate.Balance(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Balance) predicate.Balance {
	return predicate.Balance(sql.NotPredicates(p))
}
